apiVersion: apps/v1
kind: Deployment
metadata: 
  name: example-web
  labels: 
    app: kubernetes-web
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: kubernetes-web
  template:
    metadata: 
      labels:
        app: kubernetes-web
    spec: 
      containers: 
        - name: authentication-app
          image: kmilavaut/project_web:2.0
          imagePullPolicy: IfNotPresent
          ports: 
          - containerPort: 5010


