---
- name: Basic System 
  hosts: server1
  become: yes
  vars:
     ansible_user: ubuntu
     ansible_ssh_private_key_file: ./webserver1.pem
  tasks:
    - name: instalar nettools
      apt:
        name: net-tools
    - name: instalar nginx
      apt:
        name: nginx
        state: present

    - name: Encender NGiNX
      systemd:
        name: nginx
        state: started
        enabled: yes
    - name: copiar fichero
      copy:
         src:  /home/cmlavaut/Documents/DevOps/project_ejemplo/flask/main.py
         dest: /home/ubuntu