---
- name: despliegue de web
  hosts: serverkmi
  become: yes
  vars:
     ansible_user: ubuntu
     ansible_ssh_private_key_file: ./kmiweb.pem

  tasks:    
    - name: copiar web app
      synchronize:
        src: /home/cmlavaut/Documents/DevOps/web/data
        dest: /home/ubuntu
        recursive: yes


  
